name: Deploy Lambda Function

on:
  push:
    branches:
      - backend
      - main
    paths:
      - 'backend/**'

env:
  AWS_REGION: 'eu-central-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/tests/requirements.txt

      - name: Run tests
        working-directory: backend/tests
        run: |
          pytest .

      - name: Set execute permission for scripts
        working-directory: backend/scripts
        run: |
          chmod +x deploy/deploy_in_one_region_script.sh
          chmod +x build/copy_common_code_script.sh
          chmod +x build/build_script.sh

      - name: Deploy application services
        working-directory: backend/scripts/deploy
        run: |
          chmod +x deploy_in_one_region_script.sh
          ./deploy_in_one_region_script.sh
