name: Test Python Lambdas On PR

on:
  pull_request:
    branches:
      - main
      - backend
    paths:
      - 'backend/**'

jobs:
  test_lambdas:
    name: Test Python Lambdas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/tests/requirements.txt

      - name: Run tests
        working-directory: backend/tests
        run: |
          pytest .